[area]
west  = 33.5012
south = -5.0024
east  = 42.2987
north = 5.4986

[sentinelhub]
client_id     = "ba255df2-b7c9-4939-afee-b328b15560b4"
client_secret = "HS6DfifEJXT0jlazTIXk44XmlfYKAKSK"
instance_id   = "default"
max_cloud     = 20

[open_meteo]
base_url = "https://api.open-meteo.com/v1/forecast"
archive_url = "https://archive-api.open-meteo.com/v1/archive"
latitude = -0.0236
longitude = 37.9062
hourly_variables = "precipitation,temperature_2m,relative_humidity_2m,soil_moisture_0_to_10cm,wind_speed_10m"
forecast_days = 16 # Standard API supports up to 16 days

[logging]
log_file = "logs/pipeline.log"
log_level = "INFO"
max_size = 10485760
backup_count = 5

[output]
output_file = "output/latest_water_kenya.json"