[area]
# Bounding box that safely contains Kenya (EPSG:4326)
west  = 33.50
south = -5.00
east  = 42.30
north = 5.50

[sentinelhub]
client_id     = "ba255df2-b7c9-4939-afee-b328b15560b4"
client_secret = "HS6DfifEJXT0jlazTIXk44XmlfYKAKSK"
instance_id   = "default"     # or your custom best-fit instance
max_cloud     = 20            # %

[imerg]
base_url = "https://gpm.nasa.gov/PMM_PUB/API"

[open_meteo]
base_url = "https://api.open-meteo.com/v1/forecast"
